"""
parse_outputs.py
=================

Utilities for parsing and post‑processing raw model outputs.  Large language
models occasionally return malformed JSON or additional text around the
expected object.  The ``safe_parse_json`` function attempts to extract the
first valid JSON object from a text snippet.  It is used both during
annotation generation and in post‑processing steps.

This module also includes a simple CLI to convert a directory of prediction
files (as generated by ``run_llm_annotation.py``) into a more structured
format.  The CLI walks through each JSONL file in the input directory,
parses the ``raw`` field into ``parsed`` if it hasn't already been set,
and writes the updated records to a mirrored output directory.
"""

from __future__ import annotations

import argparse
import json
import pathlib
from typing import Any, Dict, Iterable, Optional, Tuple


def safe_parse_json(text: str) -> Optional[Dict[str, Any]]:
    """Attempt to parse a JSON object embedded in arbitrary text.

    Many language models wrap JSON outputs in preamble or trailing text.  This
    function searches the input for the first occurrence of ``{`` and the
    last occurrence of ``}`` and attempts to parse the substring.  If
    successful, the resulting dictionary is returned; otherwise ``None`` is
    returned.

    Parameters
    ----------
    text: str
        The raw text potentially containing JSON.

    Returns
    -------
    Optional[Dict[str, Any]]
        The parsed JSON object or ``None`` if parsing fails.
    """
    if not text:
        return None
    text = text.strip()
    # Quick check for plain JSON
    try:
        return json.loads(text)
    except Exception:
        pass
    # Fallback: search for JSON substring
    try:
        start = text.index("{")
        end = text.rindex("}") + 1
    except ValueError:
        return None
    substring = text[start:end]
    try:
        return json.loads(substring)
    except Exception:
        return None


def process_prediction_files(input_dir: pathlib.Path, output_dir: pathlib.Path) -> None:
    """Process raw prediction files, parsing the ``raw`` field into ``parsed``.

    This function reads all ``.jsonl`` files from ``input_dir`` and for each
    record, if the ``parsed`` field is empty or missing, attempts to parse
    ``raw`` using :func:`safe_parse_json`.  The updated records are written
    to ``output_dir`` preserving the original file names.  The output
    directory will be created if it does not exist.

    Parameters
    ----------
    input_dir: pathlib.Path
        Directory containing raw prediction JSONL files.
    output_dir: pathlib.Path
        Directory to write processed files to.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    for infile in input_dir.glob("*.jsonl"):
        out_path = output_dir / infile.name
        with open(infile, "r", encoding="utf-8") as fin, open(out_path, "w", encoding="utf-8") as fout:
            for line in fin:
                try:
                    record = json.loads(line)
                except json.JSONDecodeError:
                    continue
                if not record.get("parsed"):
                    record["parsed"] = safe_parse_json(record.get("raw", ""))
                fout.write(json.dumps(record, ensure_ascii=False) + "\n")


def main() -> None:
    parser = argparse.ArgumentParser(description="Parse raw prediction JSONL files.")
    parser.add_argument("--input", type=str, required=True, help="Input directory containing raw prediction files.")
    parser.add_argument("--output", type=str, required=True, help="Output directory for processed files.")
    args = parser.parse_args()
    process_prediction_files(pathlib.Path(args.input), pathlib.Path(args.output))


if __name__ == "__main__":
    main()